version: "3.8"

services:
  demo:
    image: cli-demo
    build: .
    working_dir: /app
    environment:
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
    ports:
      - "3000:3000"
      - "3100:3100"
    volumes:
      - ./:/app
